version: '2'
services:
  web:
    image: centime-resource-management:latest
    ports:
      - 8083:8083
    depends_on:
      - db
  db:
    container_name: sample_db
    image: postgres:9.4
    volumes:
      - sample_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Mi4man11
      - POSTGRES_USER=kapilankam
        - POSTGRES_DB=centime
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

volumes:
  sample_db: {}
